server:
  port: 8082
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
      - filters:
        - RemoveRequestHeader=Cookie
        id: users-status-check
        predicates:
        - Path=/users/status/check
        - Method=GET
#        uri: http://localhost:8081
        uri: lb://demo-resource-server
      - filters:
        - RemoveRequestHeader=Cookie
        id: albums
        predicates:
        - Path=/albums
        - Method=GET
#        uri: http://localhost:8091
        uri: lb://demo-resource-albums
      - filters:
        - RemoveRequestHeader=Cookie
        id: photos
        predicates:
        - Path=/photos
        - Method=GET
#        uri: http://localhost:8090
        uri: lb://demo-resource-photos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka